# Generated by Django 5.0.4 on 2024-06-02 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_categoria_options_alter_contenido_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='creacion',
        ),
    ]
