# Generated by Django 5.0.4 on 2024-06-05 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_producto_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talle', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Contenido',
                'verbose_name_plural': 'Contenidos',
            },
        ),
        migrations.RemoveField(
            model_name='producto',
            name='contenido',
        ),
        migrations.AddField(
            model_name='producto',
            name='talle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.talle'),
        ),
        migrations.DeleteModel(
            name='Contenido',
        ),
    ]
